minimumReleaseAge: 4320

overrides:
  "@sanity/preview-url-secret>@sanity/uuid": 3.0.3
  "@sanity/runtime-cli>adm-zip": 0.6.0
  "@vercel/frameworks@3.21.1>js-yaml": 3.15.0
  "next@16.2.10>postcss": 8.5.19
  "typeid-js@1.2.0>uuid": 11.1.1

allowBuilds:
  "@clerk/shared": true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
