minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@next/env@16.2.11"
  - "@next/eslint-plugin-next@16.2.11"
  - "@next/swc-darwin-arm64@16.2.11"
  - "@next/swc-darwin-x64@16.2.11"
  - "@next/swc-linux-arm64-gnu@16.2.11"
  - "@next/swc-linux-arm64-musl@16.2.11"
  - "@next/swc-linux-x64-gnu@16.2.11"
  - "@next/swc-linux-x64-musl@16.2.11"
  - "@next/swc-win32-arm64-msvc@16.2.11"
  - "@next/swc-win32-x64-msvc@16.2.11"
  - "@next/third-parties@16.2.11"
  - "eslint-config-next@16.2.11"
  - "next@16.2.11"

overrides:
  "@sanity/preview-url-secret>@sanity/uuid": 3.0.3
  "@sanity/runtime-cli>adm-zip": 0.6.0
  "@vercel/frameworks@3.21.1>js-yaml": 3.15.0
  "next@16.2.11>postcss": 8.5.20
  "next@16.2.11>sharp": 0.35.3
  "typeid-js@1.2.0>uuid": 11.1.1

allowBuilds:
  "@clerk/shared": true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
