name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Load 1Password secrets
        uses: 1password/load-secrets-action@v4
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          OP_ENV_FILE: .github/1password.env.tpl

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Validate environment
        run: pnpm exec varlock load

      - name: Lint
        run: pnpm run lint

      # - name: Test  Minimal tests with playwright to be added later
      #   run: pnpm test
